[package]
name = "rscm"
version = "0.0.0"
description = "A scheme compiler"
edition = "2024"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm18-0"] }

[dev-dependencies]
indoc = "2.0.6"
pretty_assertions = "1.4.1"
