name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - master

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: --deny warnings

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2

    - name: Clippy
      run: cargo clippy --all --all-targets

    - name: Format
      run: cargo fmt --all -- --check

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ripgrep shellcheck

    - name: Check for Forbidden Words
      run: ./bin/forbid

    - name: Check /bin scripts
      run: shellcheck bin/*

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - uses: Swatinem/rust-cache@v2

    - name: Check
      run: cargo check

  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM
      run: |
        brew install llvm@18
        echo /opt/homebrew/opt/llvm@18/bin >> $GITHUB_PATH

    - uses: Swatinem/rust-cache@v2

    - name: Test
      env:
        RUSTFLAGS: -L /opt/homebrew/lib/

      run: cargo test --all
